[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
agentnet = "GhBy186FiszBKF6ga9iG5nVQnEZNRKAnd6oPsbVW5jNp"

[programs.devnet]
agentnet = "GhBy186FiszBKF6ga9iG5nVQnEZNRKAnd6oPsbVW5jNp"

[test]
startup_wait = 15000

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS='--no-experimental-strip-types' npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
